name: Deploy Streamlit App to Azure Web App

on:
  push:
    branches:
      - main  # Triggers the workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate Streamlit App
        run: |
          source venv/bin/activate
          streamlit run streamlit_app.py --server.headless=true --server.port=8501 --server.address=127.0.0.1 &
          sleep 10  # Wait for Streamlit to start
          curl http://127.0.0.1:8501  # Check if Streamlit is responding

      - name: Zip application
        run: |
          zip -r app.zip .

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        run: |
          az webapp deployment source config-zip --resource-group oc_p9 --name p9-recommendation-streamlit --src app.zip