name: Build and deploy Streamlit App to Azure Web App

on:
  push:
    branches:
      - main  # Triggers the workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd streamlit-app
          # pip install --upgrade pip
          # pip install -r requirements.txt

      - name: Validate Streamlit App
        run: |
          cd streamlit-app
          export PORT=8501  # Set default port for GitHub workflow
          streamlit run streamlit_app.py --server.headless=true --server.address=0.0.0.0 --server.port=$PORT &
          for i in {1..15}; do
            if curl -s --head --request GET http://127.0.0.1:$PORT | grep "200 OK" > /dev/null; then
              echo "Streamlit app is running"
              break
            fi
            echo "Waiting for Streamlit app to start..."
            sleep 2
          done

      - name: Zip application
        run: |
          cd streamlit-app
          zip -r ../app.zip ./*

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        run: |
          az webapp config appsettings set --resource-group oc_p9 --name p9-recommendation-streamlit --settings "PORT=8501"
          az webapp deploy --resource-group oc_p9 --name p9-recommendation-streamlit --src-path app.zip
          az webapp restart --resource-group oc_p9 --name p9-recommendation-streamlit
